/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   bw_tests.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: kdumarai <kdumarai@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/11/27 19:58:34 by kdumarai          #+#    #+#             */
/*   Updated: 2018/01/28 14:26:27 by kdumarai         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "bw_tests.h"

/*
** DO NOT EDIT THIS FILE UNLESS NECESSARY!
*/

static void	print_dashes(int nla, int nlb, size_t len)
{
	if (nla)
		ft_putchar('\n');
	ft_putnchar('-', len);
	if (nlb)
		ft_putchar('\n');
}

int			main(void)
{
	size_t		code;
	size_t		origlen;
	size_t		newlen;
	size_t		reflen;
	size_t		nrl;
	t_padding	padtype;

	nrl = 0;
	padtype = get_padtype();
	if (padtype % 4 != 0)
	{
		ft_putstr("The padding type you chose is not valid!\n");
		return (1);
	}
	code = get_code();
	origlen = ft_nbrlen_base(code, 2);
	newlen = ft_nbrlen_base(get_bitchanged_code(code), 2);
	reflen = (newlen > origlen) ? newlen : origlen;
	if (reflen % padtype != 0)
	{
		while (nrl < reflen)
			nrl += padtype;
		reflen += nrl - reflen;
	}
	print_dashes(0, 1, reflen + 22 + reflen / padtype);
	ft_putstr("Binary rep of code bf:"); 
	ft_putbinnbr_len(code, reflen, padtype);
	code = get_bitchanged_code(code);
	ft_putstr("\nBinary rep of code af:");
	ft_putbinnbr_len(code, reflen, padtype);
	print_dashes(1, 1, reflen + 22 + reflen / padtype);
	return (0);
}
