/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   bw_tests.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: kdumarai <kdumarai@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/11/27 19:58:34 by kdumarai          #+#    #+#             */
/*   Updated: 2017/12/14 18:50:55 by kdumarai         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "bw_tests.h"

/*
** DO NOT EDIT THIS FILE UNLESS NECESSARY!
*/

int	main(void)
{
	size_t		code;
	size_t		origlen;
	t_padding	padtype;

	padtype = get_padtype();
	code = get_code();
	origlen = ft_nbrlen_base(code, 2);
	ft_putstr("-----------------------------\n");
	ft_putstr("Binary rep of code bf: "); 
	ft_putbinnbr_len(code, origlen, padtype);
	code = get_bitchanged_code(code);
	ft_putstr("\nBinary rep of code af: ");
	ft_putbinnbr_len(code, origlen, padtype);
	ft_putstr("\n-----------------------------\n");
	return (0);
}
